[Match]
Distribution=ubuntu

[Distribution]
Distribution=ubuntu
Release=noble
Repositories=main restricted universe multiverse

[Content]
CleanPackageMetadata=true
SkeletonTrees=../../resources/binaries-tree
Packages=
    linux-image-generic
    udev
    util-linux
    systemd
    dbus
    tpm2-tools
    iproute2
    iptables
    e2fsprogs
    cryptsetup
    ca-certificates
    systemd-resolved
    nvidia-container-toolkit
    libnvidia-container1
    libnvidia-container-tools
    nvidia-headless-590
    nvidia-firmware-590
    linux-modules-nvidia-590-server-6.8.0-117-generic
    nvidia-imex
    kmod
    pciutils

RemoveFiles=/etc/issue
RemoveFiles=/etc/issue.net

# Remove for reproducible builds
RemoveFiles=/var/log
RemoveFiles=/var/cache
