[Match]
Distribution=ubuntu

[Distribution]
Distribution=ubuntu
Release=noble
Repositories=main restricted universe multiverse

[Content]
CleanPackageMetadata=true
SkeletonTrees=../../resources/binaries-tree
Packages=
    udev
    util-linux
    systemd
    dbus
    tpm2-tools
    iproute2
    iptables
    e2fsprogs
    cryptsetup
    ca-certificates
    systemd-resolved

    nvidia-driver-580-server-open
    linux-modules-nvidia-580-server-6.17.0-1018-gcp
    nvidia-utils-580-server
    nvidia-fabricmanager-580
    libnvidia-nscq-580

RemoveFiles=/etc/issue
RemoveFiles=/etc/issue.net

# Remove for reproducible builds
RemoveFiles=/var/log
RemoveFiles=/var/cache
