[Match]
Distribution=ubuntu

[Distribution]
Distribution=ubuntu
Release=noble
Repositories=main restricted universe multiverse

[Content]
CleanPackageMetadata=true
SkeletonTrees=../../resources/binaries-tree
Packages=
    linux-image-6.17.0-1016-gcp
    linux-headers-6.17.0-1016-gcp
    linux-modules-nvidia-535-server-6.17.0-1016-gcp
    udev
    util-linux
    systemd
    dbus
    tpm2-tools
    iproute2
    iptables
    e2fsprogs
    cryptsetup
    ca-certificates
    systemd-resolved
    kmod
    pciutils
    nvidia-fabricmanager-535
    nvidia-utils-535-server
    libnvidia-nscq-535
    libnvidia-compute-535-server
    nvidia-compute-utils-535-server
    libnvidia-cfg1-535-server
    nvidia-container-toolkit

RemoveFiles=/etc/issue
RemoveFiles=/etc/issue.net

# Remove for reproducible builds
RemoveFiles=/var/log
RemoveFiles=/var/cache
