name: 'Automatically close stale PRs'
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  stale:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/stale@5f858e3efba33a5ca4407a664cc011ad407f2008 # v10.1.0
        with:
          stale-pr-message: 'This PR has been opened without with no activity for 90 days. Comment on the issue otherwise it will be closed in 7 days'
          days-before-pr-stale: 90
          days-before-pr-close: 7
          days-before-issue-stale: -1
          days-before-issue-close: -1
